// Tests for ../conjugate.ts (build task 2026-09-24 §C). Every expectation
// below was HAND-DERIVED from the standard godan/ichidan/suru/kuru
// conjugation rules (五段/一段/する/来る), independently of conjugate.ts's
// own implementation -- not generated by calling conjugate() and recording
// its output. This is deliberate (the build task's own spec: "用你手寫的獨
// 立期望表（不要用引擎自己產生期望）逐一比對"): a bug shared between the
// implementation and its own self-generated expectations would never be
// caught by a self-referential test.
//
// Covers every verb in data/grammar/verbs.json x all 5 forms: the original 40
// through the full EXPECTED table below, the 2026-09-25 additions through
// the hand-written readings in ./fixtures/verb-readings.ts
// (dictionary/masu/nai/te/ta), plus a kanaToCells smoke check that every
// produced reading is legal kana.

import { describe, expect, it } from "vitest";
import { conjugate, type VerbClass, type VerbForm } from "../conjugate";
import { kanaToCells } from "../../kana";
import verbsData from "../../../../data/grammar/verbs.json";
import { MORE_READINGS } from "./fixtures/verb-readings";

interface VerbFixture {
  surface: string;
  reading: string;
  class: VerbClass;
  gloss: string;
}

const verbs = (verbsData as { verbs: VerbFixture[] }).verbs;

interface FormPair {
  surface: string;
  reading: string;
}

interface Expected {
  masu: FormPair;
  nai: FormPair;
  te: FormPair;
  ta: FormPair;
}

// Hand-derived expectation table, keyed by dictionary surface. dictionary
// form itself is always the verb's own surface/reading unchanged, so it's
// not repeated here -- checked separately below via a loop over every verb.
const EXPECTED: Record<string, Expected> = {
  書く: {
    masu: { surface: "書きます", reading: "かきます" },
    nai: { surface: "書かない", reading: "かかない" },
    te: { surface: "書いて", reading: "かいて" },
    ta: { surface: "書いた", reading: "かいた" },
  },
  聞く: {
    masu: { surface: "聞きます", reading: "ききます" },
    nai: { surface: "聞かない", reading: "きかない" },
    te: { surface: "聞いて", reading: "きいて" },
    ta: { surface: "聞いた", reading: "きいた" },
  },
  泳ぐ: {
    masu: { surface: "泳ぎます", reading: "およぎます" },
    nai: { surface: "泳がない", reading: "およがない" },
    te: { surface: "泳いで", reading: "およいで" },
    ta: { surface: "泳いだ", reading: "およいだ" },
  },
  話す: {
    masu: { surface: "話します", reading: "はなします" },
    nai: { surface: "話さない", reading: "はなさない" },
    te: { surface: "話して", reading: "はなして" },
    ta: { surface: "話した", reading: "はなした" },
  },
  待つ: {
    masu: { surface: "待ちます", reading: "まちます" },
    nai: { surface: "待たない", reading: "またない" },
    te: { surface: "待って", reading: "まって" },
    ta: { surface: "待った", reading: "まった" },
  },
  死ぬ: {
    masu: { surface: "死にます", reading: "しにます" },
    nai: { surface: "死なない", reading: "しなない" },
    te: { surface: "死んで", reading: "しんで" },
    ta: { surface: "死んだ", reading: "しんだ" },
  },
  遊ぶ: {
    masu: { surface: "遊びます", reading: "あそびます" },
    nai: { surface: "遊ばない", reading: "あそばない" },
    te: { surface: "遊んで", reading: "あそんで" },
    ta: { surface: "遊んだ", reading: "あそんだ" },
  },
  読む: {
    masu: { surface: "読みます", reading: "よみます" },
    nai: { surface: "読まない", reading: "よまない" },
    te: { surface: "読んで", reading: "よんで" },
    ta: { surface: "読んだ", reading: "よんだ" },
  },
  飲む: {
    masu: { surface: "飲みます", reading: "のみます" },
    nai: { surface: "飲まない", reading: "のまない" },
    te: { surface: "飲んで", reading: "のんで" },
    ta: { surface: "飲んだ", reading: "のんだ" },
  },
  買う: {
    masu: { surface: "買います", reading: "かいます" },
    nai: { surface: "買わない", reading: "かわない" },
    te: { surface: "買って", reading: "かって" },
    ta: { surface: "買った", reading: "かった" },
  },
  会う: {
    masu: { surface: "会います", reading: "あいます" },
    nai: { surface: "会わない", reading: "あわない" },
    te: { surface: "会って", reading: "あって" },
    ta: { surface: "会った", reading: "あった" },
  },
  行く: {
    masu: { surface: "行きます", reading: "いきます" },
    nai: { surface: "行かない", reading: "いかない" },
    te: { surface: "行って", reading: "いって" }, // exception, NOT 行いて
    ta: { surface: "行った", reading: "いった" }, // exception, NOT 行いた
  },
  ある: {
    masu: { surface: "あります", reading: "あります" },
    nai: { surface: "ない", reading: "ない" }, // exception, NOT あらない
    te: { surface: "あって", reading: "あって" },
    ta: { surface: "あった", reading: "あった" },
  },
  作る: {
    masu: { surface: "作ります", reading: "つくります" },
    nai: { surface: "作らない", reading: "つくらない" },
    te: { surface: "作って", reading: "つくって" },
    ta: { surface: "作った", reading: "つくった" },
  },
  帰る: {
    masu: { surface: "帰ります", reading: "かえります" },
    nai: { surface: "帰らない", reading: "かえらない" },
    te: { surface: "帰って", reading: "かえって" },
    ta: { surface: "帰った", reading: "かえった" },
  },
  入る: {
    masu: { surface: "入ります", reading: "はいります" },
    nai: { surface: "入らない", reading: "はいらない" },
    te: { surface: "入って", reading: "はいって" },
    ta: { surface: "入った", reading: "はいった" },
  },
  走る: {
    masu: { surface: "走ります", reading: "はしります" },
    nai: { surface: "走らない", reading: "はしらない" },
    te: { surface: "走って", reading: "はしって" },
    ta: { surface: "走った", reading: "はしった" },
  },
  知る: {
    masu: { surface: "知ります", reading: "しります" },
    nai: { surface: "知らない", reading: "しらない" },
    te: { surface: "知って", reading: "しって" },
    ta: { surface: "知った", reading: "しった" },
  },
  切る: {
    masu: { surface: "切ります", reading: "きります" },
    nai: { surface: "切らない", reading: "きらない" },
    te: { surface: "切って", reading: "きって" },
    ta: { surface: "切った", reading: "きった" },
  },
  要る: {
    masu: { surface: "要ります", reading: "いります" },
    nai: { surface: "要らない", reading: "いらない" },
    te: { surface: "要って", reading: "いって" },
    ta: { surface: "要った", reading: "いった" },
  },
  立つ: {
    masu: { surface: "立ちます", reading: "たちます" },
    nai: { surface: "立たない", reading: "たたない" },
    te: { surface: "立って", reading: "たって" },
    ta: { surface: "立った", reading: "たった" },
  },
  洗う: {
    masu: { surface: "洗います", reading: "あらいます" },
    nai: { surface: "洗わない", reading: "あらわない" },
    te: { surface: "洗って", reading: "あらって" },
    ta: { surface: "洗った", reading: "あらった" },
  },
  呼ぶ: {
    masu: { surface: "呼びます", reading: "よびます" },
    nai: { surface: "呼ばない", reading: "よばない" },
    te: { surface: "呼んで", reading: "よんで" },
    ta: { surface: "呼んだ", reading: "よんだ" },
  },
  消す: {
    masu: { surface: "消します", reading: "けします" },
    nai: { surface: "消さない", reading: "けさない" },
    te: { surface: "消して", reading: "けして" },
    ta: { surface: "消した", reading: "けした" },
  },
  貸す: {
    masu: { surface: "貸します", reading: "かします" },
    nai: { surface: "貸さない", reading: "かさない" },
    te: { surface: "貸して", reading: "かして" },
    ta: { surface: "貸した", reading: "かした" },
  },
  持つ: {
    masu: { surface: "持ちます", reading: "もちます" },
    nai: { surface: "持たない", reading: "もたない" },
    te: { surface: "持って", reading: "もって" },
    ta: { surface: "持った", reading: "もった" },
  },
  食べる: {
    masu: { surface: "食べます", reading: "たべます" },
    nai: { surface: "食べない", reading: "たべない" },
    te: { surface: "食べて", reading: "たべて" },
    ta: { surface: "食べた", reading: "たべた" },
  },
  見る: {
    masu: { surface: "見ます", reading: "みます" },
    nai: { surface: "見ない", reading: "みない" },
    te: { surface: "見て", reading: "みて" },
    ta: { surface: "見た", reading: "みた" },
  },
  起きる: {
    masu: { surface: "起きます", reading: "おきます" },
    nai: { surface: "起きない", reading: "おきない" },
    te: { surface: "起きて", reading: "おきて" },
    ta: { surface: "起きた", reading: "おきた" },
  },
  寝る: {
    masu: { surface: "寝ます", reading: "ねます" },
    nai: { surface: "寝ない", reading: "ねない" },
    te: { surface: "寝て", reading: "ねて" },
    ta: { surface: "寝た", reading: "ねた" },
  },
  着る: {
    masu: { surface: "着ます", reading: "きます" },
    nai: { surface: "着ない", reading: "きない" },
    te: { surface: "着て", reading: "きて" },
    ta: { surface: "着た", reading: "きた" },
  },
  出る: {
    masu: { surface: "出ます", reading: "でます" },
    nai: { surface: "出ない", reading: "でない" },
    te: { surface: "出て", reading: "でて" },
    ta: { surface: "出た", reading: "でた" },
  },
  開ける: {
    masu: { surface: "開けます", reading: "あけます" },
    nai: { surface: "開けない", reading: "あけない" },
    te: { surface: "開けて", reading: "あけて" },
    ta: { surface: "開けた", reading: "あけた" },
  },
  教える: {
    masu: { surface: "教えます", reading: "おしえます" },
    nai: { surface: "教えない", reading: "おしえない" },
    te: { surface: "教えて", reading: "おしえて" },
    ta: { surface: "教えた", reading: "おしえた" },
  },
  借りる: {
    masu: { surface: "借ります", reading: "かります" },
    nai: { surface: "借りない", reading: "かりない" },
    te: { surface: "借りて", reading: "かりて" },
    ta: { surface: "借りた", reading: "かりた" },
  },
  いる: {
    masu: { surface: "います", reading: "います" },
    nai: { surface: "いない", reading: "いない" },
    te: { surface: "いて", reading: "いて" },
    ta: { surface: "いた", reading: "いた" },
  },
  する: {
    masu: { surface: "します", reading: "します" },
    nai: { surface: "しない", reading: "しない" },
    te: { surface: "して", reading: "して" },
    ta: { surface: "した", reading: "した" },
  },
  来る: {
    masu: { surface: "来ます", reading: "きます" },
    nai: { surface: "来ない", reading: "こない" },
    te: { surface: "来て", reading: "きて" },
    ta: { surface: "来た", reading: "きた" },
  },
  勉強する: {
    masu: { surface: "勉強します", reading: "べんきょうします" },
    nai: { surface: "勉強しない", reading: "べんきょうしない" },
    te: { surface: "勉強して", reading: "べんきょうして" },
    ta: { surface: "勉強した", reading: "べんきょうした" },
  },
  散歩する: {
    masu: { surface: "散歩します", reading: "さんぽします" },
    nai: { surface: "散歩しない", reading: "さんぽしない" },
    te: { surface: "散歩して", reading: "さんぽして" },
    ta: { surface: "散歩した", reading: "さんぽした" },
  },
};

const isHiragana = (ch: string) => /[ぁ-ゟ]/.test(ch);

/**
 * Independent okurigana rule for the MORE_READINGS verbs: the surface's
 * trailing hiragana run must match the end of its reading; everything before
 * that run (the kanji part) stays unchanged in every form, and the kana after
 * it follows the expected reading. E.g. 思い出す/おもいだす: kana tail "す",
 * kanji part 思い出 <-> おもいだ, so おもいだします -> 思い出します.
 */
function surfaceFromReading(dictSurface: string, dictReading: string, formReading: string): string {
  let k = 0;
  while (k < dictSurface.length && isHiragana(dictSurface[dictSurface.length - 1 - k])) k++;
  const tail = dictSurface.slice(dictSurface.length - k);
  if (!dictReading.endsWith(tail)) throw new Error(`${dictSurface}: 假名詞尾 ${tail} 與讀音 ${dictReading} 不一致`);
  const kanjiPart = dictSurface.slice(0, dictSurface.length - k);
  const readingPrefix = dictReading.slice(0, dictReading.length - k);
  if (!formReading.startsWith(readingPrefix)) throw new Error(`${dictSurface}: ${formReading} 不以 ${readingPrefix} 開頭`);
  return kanjiPart + formReading.slice(readingPrefix.length);
}

function expectedFor(v: VerbFixture): Expected {
  const full = EXPECTED[v.surface];
  if (full) return full;
  const [masu, nai, te, ta] = MORE_READINGS[v.surface].split(" ");
  const pair = (reading: string): FormPair => ({ surface: surfaceFromReading(v.surface, v.reading, reading), reading });
  return { masu: pair(masu), nai: pair(nai), te: pair(te), ta: pair(ta) };
}

describe("conjugate: verbs.json 全部動詞 x 5 種形", () => {
  it("每個動詞恰好在一張手寫期望表裡，兩張表也沒有多出 verbs.json 沒有的動詞", () => {
    const surfaces = new Set(verbs.map((v) => v.surface));
    expect(surfaces.size, "verbs.json 有重複的 surface").toBe(verbs.length);
    for (const v of verbs) {
      const inFull = Object.hasOwn(EXPECTED, v.surface);
      const inMore = Object.hasOwn(MORE_READINGS, v.surface);
      expect(inFull !== inMore, `${v.surface} 應恰好出現在一張期望表`).toBe(true);
    }
    for (const s of [...Object.keys(EXPECTED), ...Object.keys(MORE_READINGS)]) {
      expect(surfaces.has(s), `期望表的 ${s} 不在 verbs.json`).toBe(true);
    }
    for (const [s, forms] of Object.entries(MORE_READINGS)) {
      expect(forms.split(" "), `${s} 應有 4 個形`).toHaveLength(4);
    }
  });

  for (const v of verbs) {
    describe(`${v.surface}（${v.reading}, ${v.class}）`, () => {
      it("dictionary 形：surface/reading 原樣不變", () => {
        const result = conjugate(v, "dictionary");
        expect(result).toEqual({ surface: v.surface, reading: v.reading });
      });

      (["masu", "nai", "te", "ta"] as const satisfies readonly VerbForm[]).forEach((form) => {
        it(`${form} 形`, () => {
          const expected = expectedFor(v)[form];
          expect(conjugate(v, form)).toEqual(expected);
        });
      });
    });
  }
});

describe("conjugate: 每個輸出的 reading 都是合法假名（kanaToCells 不 throw）", () => {
  const forms: VerbForm[] = ["dictionary", "masu", "nai", "te", "ta"];
  for (const v of verbs) {
    for (const form of forms) {
      it(`${v.surface} ${form} 形的 reading 通過 kanaToCells`, () => {
        const { reading } = conjugate(v, form);
        expect(() => kanaToCells(reading)).not.toThrow();
      });
    }
  }
});
